version: "3"
services:

    gaelo:
        image: salimkanoun/gaelo
        container_name: gaelo
        restart: unless-stopped
        ports: ["127.0.0.1:8080:80"]
        volumes: ["gaelo_storage:/gaelo/data/logs:Z"]

    orthancexposed:
        image: osimis/orthanc:20.5.3
        container_name: orthancexposed
        restart: unless-stopped
        volumes: ["exposed_storage:/var/lib/orthanc/db:Z"]
        environment:
            ORTHANC__NAME: "OrthancExposed"
            ORTHANC__REGISTERED_USERS: |
                {"internal":"GaelO","external":"GaelO"}
            ORTHANC__DICOM_SERVER_ENABLED: "false"
            ORTHANC__ORTHANC_PEERS: |
                {
                    "OrthancPacs": ["http://orthancpacs:8042/", "GaelO", "GaelO"]
                }
            ORTHANC__INGEST_TRANSCODING : "1.2.840.10008.1.2.4.80"
            ORTHANC__BUILTIN_DECODER_TRANSCODER_ORDER : "Before"

    orthancpacs:
        build: orthancpacs
        container_name: orthancpacs
        depends_on: [indexorthanc]
        restart: unless-stopped
        volumes: ["pacs_storage:/var/lib/orthanc/db:Z"]
        environment:
            ORTHANC__DICOM_SERVER_ENABLED: "false"
            ORTHANC__REGISTERED_USERS: |
                {"GaelO": "GaelO", "dicomWeb": "dicomWeb"}
            TRANSFERS_PLUGIN_ENABLED: "true"
            DICOM_WEB_PLUGIN_ENABLED: "true"
            ORTHANC__NAME: "OrthancPacs"
            ORTHANC__DICOM_WEB__ENABLE: "true"
            ORTHANC__DICOM_WEB__ROOT: "/dicom-web/"
            ORTHANC__DICOM_WEB__ENABLEWADO: "true"
            ORTHANC__DICOM_WEB__WADOROOT: "/wado"
            ORTHANC__DICOM_WEB__SSL: "true"
            ORTHANC__DICOM_WEB__STUDIESMETADATA: "MainDicomTags"
            ORTHANC__DICOM_WEB__SERIESMETADATA: "Full"
            MYSQL_PLUGIN_ENABLED: "true"
            ORTHANC__MYSQL__HOST: "indexorthanc"
            ORTHANC__MYSQL__USERNAME: "orthancPacs"
            ORTHANC__MYSQL__DATABASE: "orthancPacs"
            ORTHANC__MYSQL__PASSWORD: "sassa"
            ORTHANC__BUILTIN_DECODER_TRANSCODER_ORDER : "Before"

    indexorthanc:
            image: mysql:8.0
            container_name: indexorthanc
            command: [mysqld, --default-authentication-plugin=mysql_native_password, --log-bin-trust-function-creators=1]
            volumes: ["orthanc_index:/var/lib/mysql:Z"]
            environment:
                    MYSQL_ENABLED: "true" 
                    MYSQL_PASSWORD: sassa
                    MYSQL_USER: orthancPacs
                    MYSQL_DATABASE: orthancPacs
                    MYSQL_ROOT_PASSWORD: foo-root
            restart: unless-stopped

volumes:
        exposed_storage:
        pacs_storage:
        orthanc_index:
        gaelo_storage:



